apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  creationTimestamp: "2026-03-20T00:12:52Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: airflow
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: airflow
  namespace: airflow
  resourceVersion: "797655"
  uid: 7c107b85-076b-471e-8836-c09abaea98f5
spec:
  chart:
    spec:
      chart: airflow
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
      version: 1.19.0
  install:
    timeout: 30m
  interval: 1h
  timeout: 30m
  upgrade:
    timeout: 30m
  values:
    airflowVersion: 3.1.7
    createUserJob:
      defaultUser:
        email: nsfabrice2009@gmail.com
        firstName: Admin
        lastName: User
        password: admin
        role: Admin
        username: admin
    dags:
      persistence:
        enabled: true
        size: 3Gi
        storageClassName: longhorn
    defaultAirflowTag: 3.1.7
    executor: KubernetesExecutor
    ingress:
      apiServer:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
        enabled: true
        hosts:
        - name: airflow.homelab.local
          tls:
            enabled: false
        ingressClassName: nginx
      web:
        enabled: false
    logs:
      persistence:
        enabled: true
        size: 4Gi
        storageClassName: longhorn
    postgresql:
      auth:
        database: airflow
        password: airflow
        username: airflow
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 5Gi
          storageClass: longhorn-retain
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
    scheduler:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
    webserver:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
    workers:
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
status:
  conditions:
  - lastTransitionTime: "2026-03-20T12:07:33Z"
    message: Failed to upgrade after 1 attempt(s)
    observedGeneration: 1
    reason: RetriesExceeded
    status: "True"
    type: Stalled
  - lastTransitionTime: "2026-03-20T12:07:32Z"
    message: 'Helm upgrade failed for release airflow/airflow with chart airflow@1.19.0:
      context deadline exceeded'
    observedGeneration: 1
    reason: UpgradeFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2026-03-20T12:07:32Z"
    message: 'Helm upgrade failed for release airflow/airflow with chart airflow@1.19.0:
      context deadline exceeded'
    observedGeneration: 1
    reason: UpgradeFailed
    status: "False"
    type: Released
  failures: 1
  helmChart: flux-system/airflow-airflow
  history:
  - appVersion: 3.1.7
    chartName: airflow
    chartVersion: 1.19.0
    configDigest: sha256:7dcfa893e4ee1fe5720d2381a064b9695b602eb3ce2d5962e7f7f2c87fb93b93
    digest: sha256:e343c21f44aba184287d58425c2aa483c8328540853025ad69117f55a439de60
    firstDeployed: "2026-03-20T00:12:55Z"
    lastDeployed: "2026-03-20T11:52:12Z"
    name: airflow
    namespace: airflow
    status: failed
    version: 2
  lastAttemptedConfigDigest: sha256:7dcfa893e4ee1fe5720d2381a064b9695b602eb3ce2d5962e7f7f2c87fb93b93
  lastAttemptedGeneration: 1
  lastAttemptedReleaseAction: upgrade
  lastAttemptedRevision: 1.19.0
  observedGeneration: 1
  storageNamespace: airflow
  upgradeFailures: 1
