apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/adminer
  - adminer-config-cm.yaml
  - vault-secrets.yaml
patchesStrategicMerge:
  - adminer-values.yaml
  - httproute.yaml