---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1h
  timeout: 15m
  releaseName: rancher
  targetNamespace: cattle-system
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
      version: 2.13.3
  values:
    privateCA: true
    hostname: rancher.homelab.local
    bootstrapPassword: changeme
    ingress:
      enabled: true
      tls:
        source: secrets
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 1000m
        memory: 2Gi
        ephemeral-storage: 1Gi