---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  timeout: 45m
  releaseName: rancher
  targetNamespace: cattle-system
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
      version: 2.13.3                #2.13.3
  values:
    hostname: rancher.homelab.local
    bootstrapPassword: changeme
    privateCA: true
    ingress:
      enabled: true
      tls:
        source: secret
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 1000m
        memory: 4Gi
        ephemeral-storage: 10Gi