---
# Mot de passe de la base de données phpIPAM
# Utilisé par : phpipam-web, phpipam-cron et mariadb
apiVersion: v1
kind: Secret
metadata:
  name: phpipam-secret
  namespace: phpipam
type: Opaque
data:
  # echo -n "valeur" | base64
  database-password: "bWljb2xpMTk4Nw=="