---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: phpipam
spec:
  vaultConnectionRef:
    name: vault-connection
    namespace: vault-secrets-operator-system
  method: jwt
  mount: clusterpayload
  jwt:
    role: jwt-clusterpayload-middleware-staging-phpipam
    serviceAccount: phpipam-vault-auth
    audiences:
      - middleware
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: phpipam-secret
  namespace: phpipam
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: middleware/staging/clusterpayload/phpipam/phpipam-secret
  destination:
    name: phpipam-secret
    create: true
  refreshAfter: 30s
