---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      version: "1.16.31"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
      interval: 1m
  values:
    timezone: Europe/Paris
    diagnostics:
      enabled: false
    main:
      count: 1
      editorBaseUrl: "http://n8n.homelab.local"
      env:
        N8N_SECURE_COOKIE: "false"
      persistence:
        enabled: true
        size: 5Gi
    worker:
      count: 1
    webhook:
      count: 1
    ingress:
      enabled: false
    service:
      name: http
      port: 5678
      type: ClusterIP
