---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  releaseName: netbox
  timeout: 15m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: netbox
    namespace: flux-system
  values:
    global:
      storageClass: longhorn-retain

    superuser:
      name: admin
      email: admin@homelab.local
      existingSecret: netbox-superuser-secret

    existingSecret: netbox-secret

    allowedHosts:
      - "netbox.homelab.local"

    csrf:
      trustedOrigins:
        - "http://netbox.homelab.local"

    timeZone: Europe/Paris

    postgresql:
      enabled: true
      auth:
        username: netbox
        database: netbox
        existingSecret: netbox-postgresql-secret
        secretKeys:
          adminPasswordKey: postgresql-postgres-password
          userPasswordKey: postgresql-password
      primary:
        persistence:
          enabled: true
          size: 3Gi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

    valkey:
      enabled: true
      sentinel:
        enabled: false
      auth:
        sentinel: false

    persistence:
      enabled: true
      size: 2Gi

    ingress:
      enabled: false

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi