---
# Pool d'adresses IP pour cluster-payload
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: payload-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: payload-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - payload-pool
