---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-operator
  namespace: gitlab-system
spec:
  interval: 1h
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: gitlab-operator
      version: "2.*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 1h
  # Valeurs par defaut suffisantes :
  # - watchCluster: false  → l'operator surveille uniquement gitlab-system
  # - cert-manager: install: false → on utilise notre cert-manager