---
# Mots de passe PostgreSQL pour GitLab
# postgresql-password          : mot de passe de l'user 'gitlab'
# postgresql-postgres-password : mot de passe du superuser 'postgres'
# Générer : openssl rand -hex 16
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgresql-password
  namespace: gitlab
type: Opaque
stringData:
  postgresql-password: "c343a69dce195200189c8a88c9aed614"
  postgresql-postgres-password: "c343a69dce195200189c8a88c9aed614"