---
# Mots de passe PostgreSQL pour GitLab
# postgresql-password          : mot de passe de l'user 'gitlab'
# postgresql-postgres-password : mot de passe du superuser 'postgres'
# Générer : openssl rand -hex 16
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgresql-password
  namespace: gitlab
type: Opaque
data:
  # echo -n "valeur" | base64
  postgresql-password: "YbWljb2xpMTk4Nw=="
  postgresql-postgres-password: "bWljb2xpMTk4Nw=="