---
# Secret key de chiffrement des sessions Django (50+ caractères aléatoires)
# Générer : openssl rand -hex 50
apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
  namespace: netbox
type: Opaque
data:
  # echo -n "valeur" | base64
  secret_key: "YTUyZWU2NTg0ZDM0ZWU0ZGU1ZWJlMmU0NjNkYzdmZTdiNGNkYzNlODYwYWI1MTJkYjAxNzEzODc3MDZiN2U2YzJiOTRjZGViY2M0YzI2YmIwODY2NjY2ZDFhYTM2MTJiMmZkMw=="
---
# Compte superuser admin NetBox
# superuser_password : mot de passe admin
# superuser_api_token : token API (20 octets hex) - générer : openssl rand -hex 20
apiVersion: v1
kind: Secret
metadata:
  name: netbox-superuser-secret
  namespace: netbox
type: Opaque
data:
  # echo -n "valeur" | base64
  superuser_password: "bWljb2xpMTk4Nw=="
  superuser_api_token: "Zjc0YmM1ODJiNmIwZDg2MzZkNGY4NTdlOWZjOTg2NGYxMTAyNjg3Mw=="
---
# Mots de passe PostgreSQL
# postgresql-password      : mot de passe de l'user 'netbox'
# postgresql-postgres-password : mot de passe du superuser 'postgres'
apiVersion: v1
kind: Secret
metadata:
  name: netbox-postgresql-secret
  namespace: netbox
type: Opaque
data:
  # echo -n "valeur" | base64
  postgresql-password: "bWljb2xpMTk4Nw=="
  postgresql-postgres-password: "bWljb2xpMTk4Nw=="