apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow-system
spec:
  interval: 5m
  releaseName: airflow
  targetNamespace: airflow-system
  chart:
    spec:
      chart: airflow
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
      interval: 1m
  values:
    