---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: warap-db
  namespace: warap
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: warap
      owner: warap
      secret:
        name: warap-db-secret
