---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rancher
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
    - name: rancher-tls
    - name: cilium-lb
  interval: 5m
  retryInterval: 2m
  timeout: 20m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cluster-rancher/rancher
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cluster-rancher/argocd
  prune: true
