---
# Pool d'adresses IP pour cluster-rancher
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rancher-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: rancher-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - rancher-pool
