---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: phpldapadmin
  namespace: openldap
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - ldap.homelab.local
  rules:
    - backendRefs:
        - name: openldap-ldap-stack-phpldapadmin
          port: 80
