---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    ingress:
      apiServer:
        enabled: true
        ingressClassName: nginx
        hosts:
          - name: airflow.homelab.local
            tls:
              enabled: false
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
