---
# Certificat CA racine pour home.lab
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Home Lab CA
  subject:
    organizations:
      - Home Lab
  secretName: homelab-ca-secret
  duration: 87600h  # 10 ans
  renewBefore: 8760h  # Renouveler 1 an avant expiration
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# ClusterIssuer principal utilisant la CA homelab
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca-issuer
spec:
  ca:
    secretName: homelab-ca-secret
