---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adminer
  namespace: adminer
spec:
  interval: 5m
  releaseName: adminer
  chart:
    spec:
      chart: adminer
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: startechnica
        namespace: flux-system
      interval: 1m
  values:
   