---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "82.12.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  timeout: 15m
  install:
    crds: CreateReplace
    timeout: 15m
  upgrade:
    crds: CreateReplace
    timeout: 15m
  values:
    prometheus:
      prometheusSpec:
        retention: 15d
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn-retain
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn-retain
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
    grafana:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
      adminPassword: "admin"
    prometheusOperator:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    kube-state-metrics:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
    prometheus-node-exporter:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
    ingress:
      enabled: false
